"""Public repository ports for Avuhz core and active shared systems.

Domain-company repositories implement their own persistence. Avuhz accepts
approved domain output only through ``ImplementationHandoffRepository``.
"""
from typing import Protocol


class AcquisitionHandoffRepository(Protocol):
    def get(self, tenant_id: str, handoff_id: str): ...
    def save_accepted(self, record: dict): ...


class EngagementRepository(Protocol):
    def get(self, tenant_id: str, engagement_id: str): ...
    def exists(self, tenant_id: str, engagement_id: str) -> bool: ...
    def save(self, record: dict): ...


class ImplementationHandoffRepository(Protocol):
    def get_version(self, tenant_id: str, handoff_id: str, handoff_version: int): ...
    def list_versions(self, tenant_id: str, handoff_id: str): ...
    def get_current(self, tenant_id: str, handoff_id: str): ...
    def create(self, record: dict): ...


class ImplementationBriefRepository(Protocol):
    def get_version(self, tenant_id: str, brief_id: str, brief_version: int): ...
    def list_versions(self, tenant_id: str, brief_id: str): ...
    def get_current(self, tenant_id: str, brief_id: str): ...
    def create_initial(self, record: dict): ...
    def revise(self, current: dict, replacement: dict, revised_at: str): ...
    def approve(self, current: dict, client_approval_reference: dict, provider_approval_reference: dict, approved_at: str): ...


class ImplementationAuthorizationRepository(Protocol):
    def get_version(self, tenant_id: str, authorization_id: str, authorization_version: int): ...
    def list_versions(self, tenant_id: str, authorization_id: str): ...
    def get_current(self, tenant_id: str, authorization_id: str): ...
    def create_initial(self, record: dict): ...
    def revise(self, current: dict, replacement: dict, revised_at: str): ...
    def activate(self, current: dict, client_approval_reference: dict, provider_approval_reference: dict, activated_at: str): ...
    def revoke(self, current: dict, revocation_reason: str, revoked_at: str): ...


class CodexBuildPackageRepository(Protocol):
    def get_version(self, tenant_id: str, package_id: str, package_version: int): ...
    def list_versions(self, tenant_id: str, package_id: str): ...
    def get_current(self, tenant_id: str, package_id: str): ...
    def create_initial(self, record: dict): ...
    def revise(self, current: dict, replacement: dict, revised_at: str): ...
    def release(self, current: dict, client_approval_reference: dict, provider_approval_reference: dict, released_at: str): ...


class BuildExecutionResultRepository(Protocol):
    def get(self, tenant_id: str, result_id: str): ...
    def list_by_package(self, tenant_id: str, package_id: str, package_version: int): ...
    def create(self, record: dict): ...
    def complete(self, current: dict, terminal: dict): ...


class QAResultRepository(Protocol):
    def get(self, tenant_id: str, qa_result_id: str): ...
    def list_by_package(self, tenant_id: str, package_id: str, package_version: int): ...
    def create(self, record: dict): ...


class ClientAcceptanceRepository(Protocol):
    def get_version(self, tenant_id: str, acceptance_id: str, acceptance_version: int): ...
    def list_by_package(self, tenant_id: str, package_id: str, package_version: int): ...
    def create(self, record: dict): ...


class DeploymentAuthorizationRepository(Protocol):
    def get_version(self, tenant_id: str, authorization_id: str, authorization_version: int): ...
    def list_versions(self, tenant_id: str, authorization_id: str): ...
    def get_current(self, tenant_id: str, authorization_id: str): ...
    def create_initial(self, record: dict): ...
    def revise(self, current: dict, replacement: dict, revised_at: str): ...
    def activate(self, current: dict, client_reference: dict, provider_reference: dict, activated_at: str): ...
    def revoke(self, current: dict, reason: str, revoked_at: str): ...


class DeploymentExecutionRepository(Protocol):
    def get(self, tenant_id: str, execution_id: str): ...
    def list_by_authorization(self, tenant_id: str, authorization_id: str, authorization_version: int): ...
    def create(self, record: dict): ...
    def complete(self, current: dict, terminal: dict): ...


class DeploymentVerificationRepository(Protocol):
    def get(self, tenant_id: str, verification_id: str): ...
    def list_by_execution(self, tenant_id: str, execution_id: str, execution_record_version: int): ...
    def create(self, record: dict): ...


class HumanApprovalRepository(Protocol):
    def get(self, tenant_id: str, approval_id: str): ...
    def record_phase5d(self, record: dict): ...
    def find_active_phase5d_binding(self, tenant_id: str, subject_type: str, subject_id: str, subject_version: int, digest: str, authority_role: str): ...


class IdempotencyRepository(Protocol):
    def get(self, key: tuple): ...
    def reserve(self, key: tuple, fingerprint: str, prepared=None): ...
    def save_result(self, key: tuple, result: dict): ...


class LifecycleEventRepository(Protocol):
    def append(self, event: dict): ...


class OutboxRepository(Protocol):
    def append(self, intent: dict): ...


class UnitOfWorkPort(Protocol):
    def commit(self): ...
    def rollback(self): ...
    def close(self): ...
