"""Provider-neutral Slice 1 persistence ports; no generic CRUD or database concepts."""
from typing import Protocol
class AcquisitionHandoffRepository(Protocol):
 def get(self,tenant_id:str,handoff_id:str):...
 def save_accepted(self,record:dict):...
class EngagementRepository(Protocol):
 def get(self,tenant_id:str,engagement_id:str):...
 def exists(self,tenant_id:str,engagement_id:str)->bool:...
 def save(self,record:dict):...
class DiagnosticScopeRepository(Protocol):
 def get(self,tenant_id:str,scope_id:str):...
 def save(self,record:dict):...
 def set_canonical_scope_digest(self,tenant_id:str,scope_id:str,scope_version:int,expected_record_version:int,digest:str):...
class AssessmentAccessProposalRepository(Protocol):
 def get(self,tenant_id:str,assessment_access_proposal_id:str):...

class HumanApprovalRepository(Protocol):
 def get(self,tenant_id:str,approval_id:str):...
 def save(self,record:dict):...
 def find_active_binding(self,tenant_id:str,scope_id:str,scope_version:int,authority_role:str,digest:str,action_set_version:int):...
class IdempotencyRepository(Protocol):
 def get(self,key:tuple):...
 def save_result(self,key:tuple,result:dict):...
class LifecycleEventRepository(Protocol):
 def append(self,event:dict):...
class OutboxRepository(Protocol):
 def append(self,intent:dict):...
class UnitOfWorkPort(Protocol):
 def commit(self):...
