"""Provider-neutral Slice 1 persistence ports; no generic CRUD or database concepts."""
from typing import Protocol
class AcquisitionHandoffRepository(Protocol):
 def get(self,tenant_id:str,handoff_id:str):...
 def save_accepted(self,record:dict):...
class EngagementRepository(Protocol):
 def get(self,tenant_id:str,engagement_id:str):...
 def exists(self,tenant_id:str,engagement_id:str)->bool:...
 def save(self,record:dict):...
class DiagnosticScopeRepository(Protocol):
 def get(self,tenant_id:str,scope_id:str):...
 def save(self,record:dict):...
 def set_canonical_scope_digest(self,tenant_id:str,scope_id:str,scope_version:int,expected_record_version:int,digest:str):...
class DiagnosticAgreementAuthorityRepository(Protocol):
 def get(self,tenant_id:str,diagnostic_agreement_authority_id:str):...
 def create(self,record:dict):...
class DiagnosticPaymentVerificationRepository(Protocol):
 def get(self,tenant_id:str,diagnostic_payment_verification_id:str):...
 def create(self,record:dict):...
 def invalidate(self,tenant_id:str,diagnostic_payment_verification_id:str,invalidated_at:str):...

class AssessmentAccessProposalRepository(Protocol):
 def get(self,tenant_id:str,assessment_access_proposal_id:str):...
 def create(self,proposal:dict):...

 def consume(self,tenant_id:str,assessment_access_proposal_id:str,digest:str,consumed_at:str):...

class AssessmentAccessGrantRepository(Protocol):
 def get(self,tenant_id:str,assessment_access_grant_id:str):...
 def create(self,grant:dict):...
 def activate(self,tenant_id:str,assessment_access_grant_id:str,digest:str,verified_at:str,expires_at:str):...
 def expire(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def revoke(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def close_for_agreement_end(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def expire(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def revoke(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def close_for_agreement_end(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
class AssessmentAccessVerifier(Protocol):
 def verify(self,request):...

class OIAAssessmentRepository(Protocol):
 def get(self,tenant_id:str,oia_assessment_id:str):...
 def find_by_assessment_access_grant(self,tenant_id:str,assessment_access_grant_id:str):...
 def create(self,assessment:dict):...

class OIAEvidenceRepository(Protocol):
 def get(self,tenant_id:str,oia_evidence_id:str):...
 def create(self,evidence:dict):...

class OIAAssessmentPlanRepository(Protocol):
 def get_version(self,tenant_id:str,oia_assessment_plan_id:str,plan_version:int):...
 def get_current(self,tenant_id:str,oia_assessment_plan_id:str):...
 def find_current_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def list_versions(self,tenant_id:str,oia_assessment_plan_id:str):...
 def create_initial(self,plan:dict):...
 def revise(self,current:dict,replacement:dict,revised_at:str):...
 def review(self,current:dict,reviewed_by:str,reviewed_at:str):...
 def approve(self,current:dict,approved_by:str,approved_at:str):...

class OIAInspectionItemRepository(Protocol):
 def get(self,tenant_id:str,oia_inspection_item_id:str):...
 def list_by_plan(self,tenant_id:str,oia_assessment_plan_id:str,plan_version:int):...
 def list_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def create(self,item:dict):...
 def update(self,current:dict,payload:dict,updated_by:str,updated_at:str):...
 def block(self,current:dict,payload:dict,updated_by:str,updated_at:str,stop_reason:str|None):...
 def coverage_for_plan(self,tenant_id:str,oia_assessment_plan_id:str,plan_version:int):...
 def coverage_for_current_assessment(self,tenant_id:str,oia_assessment_id:str):...

class OIAObservationRepository(Protocol):
 def get(self,tenant_id:str,oia_observation_id:str):...
 def list_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def list_current_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def resolve_current(self,tenant_id:str,oia_observation_id:str):...
 def create(self,observation:dict):...
 def supersede(self,original:dict,replacement:dict,superseded_at:str):...

class OIARootCauseRepository(Protocol):
 def get(self,tenant_id:str,oia_root_cause_id:str):...
 def list_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def create(self,root_cause:dict):...
 def transition(self,current:dict,payload:dict,updated_at:str):...

class HumanApprovalRepository(Protocol):
 def get(self,tenant_id:str,approval_id:str):...
 def record_assessment_access(self,record:dict):...
 def find_active_assessment_access_binding(self,tenant_id:str,proposal_id:str,digest:str,authority_role:str):...
 def list_active_assessment_access_bindings(self,tenant_id:str,proposal_id:str,digest:str,authority_role:str):...
 def save(self,record:dict):...
 def find_active_binding(self,tenant_id:str,scope_id:str,scope_version:int,authority_role:str,digest:str,action_set_version:int):...
class IdempotencyRepository(Protocol):
 def get(self,key:tuple):...
 def save_result(self,key:tuple,result:dict):...
class LifecycleEventRepository(Protocol):
 def append(self,event:dict):...
class OutboxRepository(Protocol):
 def append(self,intent:dict):...
class UnitOfWorkPort(Protocol):
 def commit(self):...
